auth:
  firebase:
    apiKey: AIzaSyCKZng55l411pps2HgMcuenMQou-NTQ0QE
    authDomain: creatorsgarten-wiki.firebaseapp.com
    projectId: creatorsgarten-wiki
policies:
  - name: Allow dtinth to edit the wiki
    permission: edit
    userId: 193136
